### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by saurabh3679** [cobidev/simplefolio#100]
npm install command fails with following error:
```
3753 timing command:install Completed in 54409ms
3754 verbose stack Error: command failed
3754 verbose stack     at ChildProcess.<anonymous> (C:\Users\Saurabh\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
3754 verbose stack     at ChildProcess.emit (node:events:394:28)
3754 verbose stack     at maybeClose (node:internal/child_process:1067:16)
3754 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3755 verbose pkgid node-sass@4.14.1
3756 verbose cwd C:\Users\Saurabh\non-React_webProjects\simplefolio
3757 verbose Windows_NT 10.0.19041
3758 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Saurabh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
3759 verbose node v16.3.0
3760 verbose npm  v7.16.0
3761 error code 1
3762 error path C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\node-sass
3763 error command failed
3764 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
3765 error Building: C:\Program Files\nodejs\node.exe C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
3766 error gyp info it worked if it ends with ok
3766 error gyp verb cli [
3766 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
3766 error gyp verb cli   'C:\\Users\\Saurabh\\non-React_webProjects\\simplefolio\\node_modules\\node-gyp\\bin\\node-gyp.js',
3766 error gyp verb cli   'rebuild',
3766 error gyp verb cli   '--verbose',
3766 error gyp verb cli   '--libsass_ext=',
3766 error gyp verb cli   '--libsass_cflags=',
3766 error gyp verb cli   '--libsass_ldflags=',
3766 error gyp verb cli   '--libsass_library='
3766 error gyp verb cli ]
3766 error gyp info using node-gyp@3.8.0
3766 error gyp info using node@16.3.0 | win32 | x64
3766 error gyp verb command rebuild []
3766 error gyp verb command clean []
3766 error gyp verb clean removing "build" directory
3766 error gyp verb command configure []
3766 error gyp verb check python checking for Python executable "python2" in the PATH
3766 error gyp verb `which` failed Error: not found: python2
3766 error gyp verb `which` failed     at getNotFoundError (C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:13:12)
3766 error gyp verb `which` failed     at F (C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:68:19)
3766 error gyp verb `which` failed     at E (C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:80:29)
3766 error gyp verb `which` failed     at C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:89:16
3766 error gyp verb `which` failed     at C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\isexe\index.js:42:5
3766 error gyp verb `which` failed     at C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\isexe\windows.js:36:5
3766 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
3766 error gyp verb `which` failed  python2 Error: not found: python2
3766 error gyp verb `which` failed     at getNotFoundError (C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:13:12)
3766 error gyp verb `which` failed     at F (C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:68:19)
3766 error gyp verb `which` failed     at E (C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:80:29)
3766 error gyp verb `which` failed     at C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\which\which.js:89:16
3766 error gyp verb `which` failed     at C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\isexe\index.js:42:5
3766 error gyp verb `which` failed     at C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\isexe\windows.js:36:5
3766 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
3766 error gyp verb `which` failed   code: 'ENOENT'
3766 error gyp verb `which` failed }
3766 error gyp verb check python checking for Python executable "python" in the PATH
3766 error gyp verb `which` succeeded python C:\Python38\python.EXE
3766 error gyp ERR! configure error
3766 error gyp ERR! stack Error: Command failed: C:\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
3766 error gyp ERR! stack   File "<string>", line 1
3766 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
3766 error gyp ERR! stack                       ^
3766 error gyp ERR! stack SyntaxError: invalid syntax
3766 error gyp ERR! stack
3766 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
3766 error gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
3766 error gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
3766 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3766 error gyp ERR! System Windows_NT 10.0.19041
3766 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Saurabh\\non-React_webProjects\\simplefolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3766 error gyp ERR! cwd C:\Users\Saurabh\non-React_webProjects\simplefolio\node_modules\node-sass
3766 error gyp ERR! node -v v16.3.0
3766 error gyp ERR! node-gyp -v v3.8.0
3766 error gyp ERR! not ok
3766 error Build failed with error code: 1
3767 verbose exit 1
```

**Comment by pjwmascall** [comment]
I've had the same issue with the same errors on windows 10

**Comment by cobidev** [comment]
@pjwmascall @saurabh3679 the issue seems to be coming from Python. And Simplefolio do not use Python for any dependency.

So my question would be:

What are the installation steps are you doing? did you follow this tutorial: https://www.youtube.com/watch?v=soaG3GNSxJY ?

**Comment by pjwmascall** [comment]
@cobidev I followed the installation steps as described. I also tried reconfiguring and reinstalling python, and it didn't seem to help. I updated anaconda (running python 3.7), installed python 3.9 and python 2.7, tried adding them to the windows path (https://datatofish.com/add-python-to-windows-path/), and I still can't install simplefolio, sadly.

**Comment by pjwmascall** [comment]
@cobidev @saurabh3679 I found a fix. The first thing I did was run the command:
`npm install --global windows-build-tools`
in git bash (https://stackoverflow.com/questions/54262174/i-am-getting-python2-failed-errors-on-npm-install).
Then I received an error message telling me that in order to use windows-build-tools, I had to right-click Windows PowerShell and run as administrator.
I did this, and then with Windows PowerShell open, I ran the command:
`npm install`
in git bash, and it installed correctly.

**Comment by cobidev** [comment]
@saurabh3679 I hope this works for you too. Let me know if it's fixed so I can close this Issue!

Thanks for researching @pjwmascall 💪 (I use MAC, so I wasn't be able to reproduce the build error)

**Comment by lukasz6678** [comment]
I have problems with open on Win10, too. 
Here are logs from powershell:
PS C:\Users\Lukasz\Desktop\web developer> git clone https://github.com/lukasz6678/simplefolio 
Cloning into 'simplefolio'...
remote: Enumerating objects: 1019, done.
remote: Total 1019 (delta 0), reused 0 (delta 0), pack-reused 1019Receiving objects: 100% (1019/1019), 15.29 MiB | 6.06 MiB/s
Receiving objects: 100% (1019/1019), 16.54 MiB | 5.96 MiB/s, done.
Resolving deltas: 100% (554/554), done.
PS C:\Users\Lukasz\Desktop\web developer> cd simplefolio
PS C:\Users\Lukasz\Desktop\web developer\simplefolio> npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\msgpackr-extract',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\msgpackr-extract'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\msgpackr-extract'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\lmdb',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\lmdb'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\lmdb'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\lmdb'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\lmdb'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\@parcel',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\@parcel\plugin\lib'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\@parcel\\plugin\\lib'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\@parcel\\node-resolver-core',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\@parcel\node-resolver-core\test\fixture\node_modules\side-effects-package-redirect-up\foo\bar'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Lukasz\\Desktop\\web developer\\simplefolio\\node_modules\\@parcel\\node-resolver-core\\test\\fixture\\node_modules\\side-effects-package-redirect-up\\foo\\bar'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\@parcel\watcher
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.14.0 | win32 | ia32
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Lukasz\AppData\Local\Programs\Python\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\Lukasz\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Lukasz\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Lukasz\Desktop\web developer\simplefolio\node_modules\@parcel\watcher
npm ERR! gyp ERR! node -v v18.14.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lukasz\AppData\Local\npm-cache\_logs\2023-02-04T21_12_27_077Z-debug-0.log


thanks for help!
