### ISSUE TITLE
No Bundle Entries Found

### ISSUE THREAD

**Issue by PeterVermeulen01123** [cobidev/simplefolio#141]
Hello, I'm running into issues installing the dependencies. 
I ran the command 
$ npm install --unsafe-perm=true --allow-root

also ran:
$ npm install -g webpack
$ npm install --unsafe-perm=true --allow-root --legacy-peer-deps

kept getting issues installing dependencies, and ran
$ npm audit fix
$ npm audit fix --force

when I ran 
$ npm start

this is what resulted:

×  No entries found.
    at Bundler.bundle (C:\Users\gregv\OneDrive\Desktop\ZtM\simplefolio\node_modules\parcel\src\Bundler.js:275:17)
    at async Bundler.serve (C:\Users\gregv\OneDrive\Desktop\ZtM\simplefolio\node_modules\parcel\src\Bundler.js:842:7)
    at async Command.bundle (C:\Users\gregv\OneDrive\Desktop\ZtM\simplefolio\node_modules\parcel\src\cli.js:241:20)

I have no idea what to do. Can anyone please help and guide me in the right direction?

**Comment by Aliiiu** [comment]
Please where you able to fix the issue? I am also having something similar to this

**Comment by cobiwave** [comment]
Hey @PeterVermeulen01123 @Aliiiu 

Sorry for replying at this late. Do you still need some help or guidance?

Right now I am working on major updates (mostly fixing all the issues Simplefolio has).

I will let know to all the community via Discord.
