### ISSUE TITLE
Cannot start npm

### ISSUE THREAD

**Issue by adryana24** [cobidev/simplefolio#177]
I installed npm and all looks good:

$ npm install

up to date, audited 178 packages in 1s

78 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

But I have this error when I start npm:
$ npm start

> simplefolio@1.0.1 start
> parcel

Error: The specified module could not be found.
\\?\C:\Users\admin\Desktop\simplefolio\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\index.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Desktop\simplefolio\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\admin\Desktop\simplefolio\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
    at Module._compile (C:\Users\admin\Desktop\simplefolio\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Can someoane help me please?
Thank you

**Comment by Brandon-Boyle** [comment]
did you ever find the answer for this?

**Comment by Brandon-Boyle** [comment]
im havinv the same issue

**Comment by saiteja13427** [comment]
I think there can be two problems
1. Either you are using a old version of node.
2. Or try removing node modules, package.json, pakcage.lock.json and try running npm i again and then try running it.
