### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by 1dudecoder** [cobidev/simplefolio#88]
throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8080/' ]
}

**Comment by gambo94** [comment]
same issue, anyone could help please?

**Comment by SanyogDeshmukh** [comment]
1. Go to My Computer Properties.
2. Click Advanced System Settings
3. Environment Variables - Here add path "C:\Windows\System32" for both user and system variables

**Comment by cobidev** [comment]
@SanyogDeshmukh thanks for the suggestion! I see it's a Window issue...

@gambo94 @1dudecoder does that instructions solve the issue for you both?

Let me know, so I can close this issue.
